SM_PresentationLayer/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SM_PresentationLayer.Controllers
{
    public class CalendarController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SM_PresentationLayer/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SM_DomainLayer.Entities.Concrete;
using SM_InfrastuctureLayer.Context;

namespace SM_PresentationLayer.Controllers
{
    public class MessageController : Controller
    {
       
        public readonly ApplicationDbContext _context;
        public readonly UserManager<AppUser> _userManager;
        public MessageController(UserManager<AppUser> userManager,
                                 ApplicationDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }
        [Authorize]

        public async Task<IActionResult> Messenger()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUserName = currentUser.UserName;
            }
            
            var messages = await _context.Messages.ToListAsync();
            return View(messages);
        }


        public async Task<IActionResult> Create(Message message)
        {
            if (ModelState.IsValid)
            {
                message.UserName = User.Identity.Name;
                var sender = await _userManager.GetUserAsync(User);
                message.UserId = sender.Id;
                await _context.Messages.AddAsync(message);
                await _context.SaveChangesAsync();
                return Ok();
            }
            return BadRequest("Opps something has been wrong..");
        }

    }
}

SM_PresentationLayer/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SM_ApplicationLayer.Services.Abstract;

namespace SM_PresentationLayer.Controllers
{
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class ProfileController : Controller
    {
        private readonly IAppUserService _userService;
        public ProfileController(IAppUserService userService)
        {
            _userService = userService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Detail(string userName)
        {
            ViewBag.userName = userName;
            return View();
        }

        public IActionResult Followings(string userName)
        {
            ViewBag.userName = userName;
            return View();
        }

        public IActionResult Followers(string userName)
        {
            ViewBag.userName = userName;
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Followers(string userName,int pageIndex)
        {
            var findUser = await _userService.UserIdFromName(userName);
            if (findUser>0)
            {
                var followers = await _userService.UsersFollowers(findUser, pageIndex);
                return Json(followers, new JsonSerializerSettings());

            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Followings(string userName,int pageIndex)
        {
            var findUser = await _userService.UserIdFromName(userName);
            if (findUser>0)
            {
                var followings = await _userService.UsersFollowings(findUser, pageIndex);

                return Json(followings, new JsonSerializerSettings());

            }
            else
            {
                return NotFound();
            }

        }
    }
}

SM_PresentationLayer/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SM_ApplicationLayer.Services.Abstract;

namespace SM_PresentationLayer.Controllers
{
    public class SearchController : Controller
    {
        private readonly IAppUserService _userService;

        public SearchController(IAppUserService userService)
        {
            _userService = userService;
        }
        public IActionResult Index(string userName)
        {
            ViewBag.SearchKeyword = userName;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string userName,int pageIndex)
        {
            if (!String.IsNullOrEmpty(userName))
            {
                var users = await _userService.SearchUser(userName, pageIndex);
                return Json(users, new JsonSerializerSettings());

            }
            else
            {
                return NotFound();
            }
        }
    }
}

SM_PresentationLayer/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Facebook| Homepage </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link href="~/asset/fonts/fontawesome-free/css/fontawesome.css" rel="stylesheet" />
    
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->

    <link href="~/asset/css/adminlte.min.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-navbar-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>

                <li class="nav-item">
                    <form method="post" asp-controller="Home" asp-action="Index">
                        <button type="submit" class="btn  btn-secondary btn-sm">Home</button>
                    </form>
                </li>

                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="nav-item">
                        <form method="post" asp-controller="Account" asp-action="Logout">
                            <button type="submit" class="btn  btn-primary btn-sm">Sign Out</button>
                        </form>
                    </li>

                    <li class="nav-item dropdown">
                        <div class="dropdown">
                            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Profile
                            </button>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" method="post" asp-controller="Account" asp-action="EditProfile" asp-route-userName="@User.Identity.Name">Edit Profile</a>
                                <a class="dropdown-item" asp-controller="Profile" asp-action="Detail" asp-route-UserName="@User.Identity.Name">Details</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </div>
                    </li>

                    <li class="nav-item">
                        <form method="post" asp-controller="Message" asp-action="Messenger" asp-route-userName="@User.Identity.Name">
                            <button type="submit" class="btn btn-secondary btn-sm">Messenger</button>
                        </form>
                    </li>

                }
                else
                {
                    <li class="nav-item">
                        <form method="post" asp-controller="Account" asp-action="Register">
                            <button type="submit" class="btn  btn-danger btn-sm">SignUp</button>
                        </form>
                    </li>
                    <li class="nav-item">
                        <form method="post" asp-controller="Account" asp-action="Login">
                            <button type="submit" class="btn  btn-dark btn-sm">SignIn</button>
                        </form>
                    </li>
                }
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3" id="searchform" asp-controller="Search" asp-action="Index" method="get">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" name="UserName" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav item">
                    <div class="nav-item">
                     
                        <form method="post" asp-controller="Calendar" asp-action="Index">
                            <button type="submit" class="btn  btn-primary btn-sm">Schedule</button>
                        </form>

                      </div>
                </li>
            </ul>
        </nav>

                <!-- /.navbar -->
                <!-- Main Sidebar Container -->
                <aside class="main-sidebar sidebar-dark-primary elevation-4">
                    <!-- Brand Logo -->
                    <a href="../../index3.html" class="brand-link elevation-4">
                        <img src="~/images/logo/facebook.png" />
                        alt="wellcome to FaceBook"
                        class="brand-image img-circle elevation-3"
                        style="opacity: .8">
                        <span class="brand-text font-weight-light">FaceBook</span>
                    </a>

                    <!-- Sidebar -->
                    <div class="sidebar">
                        <!-- Sidebar user (optional) -->
                        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                            <div class="image">
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    
                                    <img src="~/images/logo/facebook.png" class="img-circle elevation-2" />
                                    }
                                    else
                                    {
                                    <img src="~/images/users/default.jpg" class="img-circle elevation-2" alt="User Image">
                                    }

                                </div>
                            <div class="info">
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <a href="Profile/Detail" class="d-block">@User.Identity.Name</a>
                                }
                                else
                                {

                                    <a href="#" class="d-block">Wellcome</a>
                                }
                            </div>
                        </div>

                        <!-- Sidebar Menu -->
                        <nav class="mt-2">

                        </nav>
                        <!-- /.sidebar-menu -->
                    </div>
                    <!-- /.sidebar -->
                </aside>

                <!-- Content Wrapper. Contains page content -->
                <div class="content-wrapper">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        @RenderBody()
                    </section>
                    <section>
                        <div class="content-wrapper" id="loadPostList">
                        </div>
                    </section>

                    <!-- Main content -->
                    <!-- /.content -->
                </div>
                <!-- /.content-wrapper -->
                <!-- Control Sidebar -->
                <aside class="control-sidebar control-sidebar-dark">
                    <!-- Control sidebar content goes here -->
                </aside>
                <!-- /.control-sidebar -->
</div>
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/asset/scripts/jquery.min.js"></script>
    <!-- Bootstrap 4 -->

    <script src="~/asset/scripts/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->

    <script src="~/asset/scripts/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->

    <script src="~/asset/scripts/demo.js"></script>
    <script src="~/js/get-posts.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>